//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLearn.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodeLearnEntities : DbContext
    {
        public CodeLearnEntities()
            : base("name=CodeLearnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data_type> data_type { get; set; }
        public virtual DbSet<exercise> exercises { get; set; }
        public virtual DbSet<exercise_type> exercise_type { get; set; }
        public virtual DbSet<test_case_parameters> test_case_parameters { get; set; }
        public virtual DbSet<test_cases> test_cases { get; set; }
        public virtual DbSet<test_method_info> test_method_info { get; set; }
        public virtual DbSet<test_method_parameters> test_method_parameters { get; set; }
    }
}
