//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLearn.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exercise()
        {
            this.test_method_info = new HashSet<test_method_info>();
        }
    
        public int id { get; set; }
        public string exercise_description { get; set; }
        public string context { get; set; }
        public string coding_area { get; set; }
        public int exercise_type_id { get; set; }
        public string optional_usings { get; set; }
        public string optional_dlls { get; set; }
        public string class_name { get; set; }
    
        public virtual exercise_type exercise_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_method_info> test_method_info { get; set; }
    }
}
