//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLearn.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_method_parameters
    {
        public int id { get; set; }
        public int data_type_id { get; set; }
        public int test_method_info_id { get; set; }
        public int position { get; set; }
    
        public virtual data_type data_type { get; set; }
        public virtual test_method_info test_method_info { get; set; }
    }
}
