//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLearn.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_case_parameter
    {
        public int id { get; set; }
        public int test_case_id { get; set; }
        public string value { get; set; }
        public int position { get; set; }
    
        public virtual test_case test_case { get; set; }
    }
}
