// <auto-generated />
using System;
using CodeLearn.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeLearn.Db.Migrations
{
    [DbContext(typeof(CodeLearnContext))]
    partial class CodeLearnContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeLearn.Db.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int?>("GroupId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("patronymic");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CodeLearn.Db.DataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("short_name");

                    b.HasKey("Id");

                    b.ToTable("data_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Void",
                            ShortName = "void"
                        },
                        new
                        {
                            Id = 2,
                            Name = "System.Boolean",
                            ShortName = "bool"
                        },
                        new
                        {
                            Id = 3,
                            Name = "System.Byte",
                            ShortName = "byte"
                        },
                        new
                        {
                            Id = 4,
                            Name = "System.SByte",
                            ShortName = "sbyte"
                        },
                        new
                        {
                            Id = 5,
                            Name = "System.Char",
                            ShortName = "char"
                        },
                        new
                        {
                            Id = 6,
                            Name = "System.Decimal",
                            ShortName = "decimal"
                        },
                        new
                        {
                            Id = 7,
                            Name = "System.Double",
                            ShortName = "double"
                        },
                        new
                        {
                            Id = 8,
                            Name = "System.Single",
                            ShortName = "float"
                        },
                        new
                        {
                            Id = 9,
                            Name = "System.Int32",
                            ShortName = "int"
                        },
                        new
                        {
                            Id = 10,
                            Name = "System.UInt32",
                            ShortName = "uint"
                        },
                        new
                        {
                            Id = 11,
                            Name = "System.Int64",
                            ShortName = "long"
                        },
                        new
                        {
                            Id = 12,
                            Name = "System.UInt64",
                            ShortName = "ulong"
                        },
                        new
                        {
                            Id = 13,
                            Name = "System.Int16",
                            ShortName = "short"
                        },
                        new
                        {
                            Id = 14,
                            Name = "System.UInt16",
                            ShortName = "ushort"
                        },
                        new
                        {
                            Id = 15,
                            Name = "System.IntPtr",
                            ShortName = "nint"
                        },
                        new
                        {
                            Id = 16,
                            Name = "System.Object",
                            ShortName = "object"
                        },
                        new
                        {
                            Id = 17,
                            Name = "System.String",
                            ShortName = "string"
                        },
                        new
                        {
                            Id = 18,
                            Name = "System.Object",
                            ShortName = "dynamic"
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("class_name");

                    b.Property<string>("CodingArea")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("coding_area");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("int")
                        .HasColumnName("exercise_type_id");

                    b.Property<string>("OptionalDlls")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("optional_dlls");

                    b.Property<string>("OptionalUsings")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("optional_usings");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("short_description");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("exercise", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "TestClass",
                            CodingArea = "public static double GetArea(double a, double b)\n{\n    // Example\n    return a * b;\n}",
                            Context = "// tests example\nstatic void Main()\n{\n Console.WriteLine(GetArea(6, 6));\n Console.WriteLine(GetArea(7.5, 10));\n Console.WriteLine(GetArea(1, 5));\n}",
                            Description = "Напишите тело метода GetArea так, чтобы оно возвращало площадь прямоугольника. Можете считать, что параметры ''''a'''' и ''''b'''' всегда положительные числа.",
                            ExerciseTypeId = 1,
                            Score = 1,
                            ShortDescription = "Вычисление площади"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "TestClass",
                            CodingArea = "public static double GetNumber(long a)\n{\n    // example\n    return --a;\n}",
                            Context = "// example\nGetNumber(3);\nGetNumber(75);\nGetNumber(100);",
                            Description = "Для простого примера, выведите число, которой будет на 1 меньше.",
                            ExerciseTypeId = 1,
                            Score = 1,
                            ShortDescription = "Простой вывод"
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("exercise_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Method coding"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Class coding"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Question"
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test group",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("result");

                    b.Property<int>("TestMethodId")
                        .HasColumnType("int")
                        .HasColumnName("test_method_id");

                    b.HasKey("Id");

                    b.HasIndex("TestMethodId");

                    b.ToTable("test_cases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Result = "9",
                            TestMethodId = 1
                        },
                        new
                        {
                            Id = 2,
                            Result = "10",
                            TestMethodId = 1
                        },
                        new
                        {
                            Id = 3,
                            Result = "5",
                            TestMethodId = 2
                        },
                        new
                        {
                            Id = 4,
                            Result = "8",
                            TestMethodId = 2
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.TestCaseParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int")
                        .HasColumnName("test_case_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("test_case_parameters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Position = 0,
                            TestCaseId = 1,
                            Value = "3"
                        },
                        new
                        {
                            Id = 2,
                            Position = 1,
                            TestCaseId = 1,
                            Value = "3"
                        },
                        new
                        {
                            Id = 3,
                            Position = 0,
                            TestCaseId = 2,
                            Value = "5"
                        },
                        new
                        {
                            Id = 4,
                            Position = 1,
                            TestCaseId = 2,
                            Value = "2"
                        },
                        new
                        {
                            Id = 5,
                            Position = 0,
                            TestCaseId = 3,
                            Value = "6"
                        },
                        new
                        {
                            Id = 6,
                            Position = 0,
                            TestCaseId = 4,
                            Value = "9"
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.Testing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("description");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("TestCreatorId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("test_creator_id");

                    b.HasKey("Id");

                    b.HasIndex("TestCreatorId");

                    b.ToTable("testing", (string)null);
                });

            modelBuilder.Entity("CodeLearn.Db.TestingAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    b.Property<string>("FailureInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("failure_info");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<int>("TestingResultId")
                        .HasColumnType("int")
                        .HasColumnName("testing_result_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TestingResultId");

                    b.ToTable("testing_answer", (string)null);
                });

            modelBuilder.Entity("CodeLearn.Db.TestingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("PassingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("passing_date");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("student_id");

                    b.Property<int>("TestingId")
                        .HasColumnType("int")
                        .HasColumnName("testing_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TestingId");

                    b.ToTable("testing_result", (string)null);
                });

            modelBuilder.Entity("CodeLearn.Db.TestMethodInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.Property<int>("ReturnTypeId")
                        .HasColumnType("int")
                        .HasColumnName("return_type_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ReturnTypeId");

                    b.ToTable("test_method_info", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            Name = "GetArea",
                            ReturnTypeId = 7
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            Name = "GetNumber",
                            ReturnTypeId = 11
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.TestMethodParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DataTypeId")
                        .HasColumnType("int")
                        .HasColumnName("data_type_id");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int>("TestMethodInfoId")
                        .HasColumnType("int")
                        .HasColumnName("test_method_info_id");

                    b.HasKey("Id");

                    b.HasIndex("DataTypeId");

                    b.HasIndex("TestMethodInfoId");

                    b.ToTable("test_method_parameters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataTypeId = 7,
                            Position = 0,
                            TestMethodInfoId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataTypeId = 7,
                            Position = 1,
                            TestMethodInfoId = 1
                        },
                        new
                        {
                            Id = 3,
                            DataTypeId = 11,
                            Position = 0,
                            TestMethodInfoId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TestingExercise", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    b.HasKey("CourseId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("testing_exercise", (string)null);
                });

            modelBuilder.Entity("CodeLearn.Db.Student", b =>
                {
                    b.HasBaseType("CodeLearn.Db.ApplicationUser");

                    b.HasIndex("GroupId");

                    b.ToTable("student", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a3b34355-c2e0-402d-99e0-7c3d37dcc959",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "063920bb-eaa9-4f30-bcc2-d881c90dc354",
                            Email = "student@example.com",
                            EmailConfirmed = true,
                            FirstName = "studentFirstName",
                            GroupId = 1,
                            IsTeacher = true,
                            LastName = "studentLastName",
                            LockoutEnabled = true,
                            NormalizedEmail = "STUDENT@EXAMPLE.COM",
                            NormalizedUserName = "STUDENT",
                            PasswordHash = "AQAAAAEAACcQAAAAEL7eUCPFYJbI+JuDj5dCq+dt+S7ncZ2i54iPWDB61i3siAN+YgDZ/VFOs1iPdxxGpg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad967813-9c21-4e78-96b4-484289e305cd",
                            TwoFactorEnabled = false,
                            UserName = "student"
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.Teacher", b =>
                {
                    b.HasBaseType("CodeLearn.Db.ApplicationUser");

                    b.ToTable("teacher", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0f3ee92e-c737-4f35-adff-b13c32f8897b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a03f73a-6a32-434b-8233-24fd507b4dd4",
                            Email = "teacher@example.com",
                            EmailConfirmed = true,
                            FirstName = "teacherFirstName",
                            GroupId = 0,
                            IsTeacher = true,
                            LastName = "teacherLastName",
                            LockoutEnabled = true,
                            NormalizedEmail = "TEACHER@EXAMPLE.COM",
                            NormalizedUserName = "TEACHER",
                            PasswordHash = "AQAAAAEAACcQAAAAEN2w22vIqSGLHwd2vUsJaoo4l4j09ZfN6Ia6dT870LwfBSZGdJF3ZNddnnF3NMB0Dw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a74d66d-ec81-4301-b11a-ea77a4a5dc62",
                            TwoFactorEnabled = false,
                            UserName = "teacher"
                        });
                });

            modelBuilder.Entity("CodeLearn.Db.Exercise", b =>
                {
                    b.HasOne("CodeLearn.Db.ExerciseType", "ExerciseType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Exercises_ExerciseTypes");

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("CodeLearn.Db.TestCase", b =>
                {
                    b.HasOne("CodeLearn.Db.TestMethodInfo", "TestMethod")
                        .WithMany("TestCases")
                        .HasForeignKey("TestMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_test_case_test_method_info");

                    b.Navigation("TestMethod");
                });

            modelBuilder.Entity("CodeLearn.Db.TestCaseParameter", b =>
                {
                    b.HasOne("CodeLearn.Db.TestCase", "TestCase")
                        .WithMany("TestCaseParameters")
                        .HasForeignKey("TestCaseId")
                        .IsRequired()
                        .HasConstraintName("FK_Parameters_TestCases");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("CodeLearn.Db.Testing", b =>
                {
                    b.HasOne("CodeLearn.Db.Teacher", "TestCreator")
                        .WithMany("Testings")
                        .HasForeignKey("TestCreatorId")
                        .HasConstraintName("FK_testing_teacher");

                    b.Navigation("TestCreator");
                });

            modelBuilder.Entity("CodeLearn.Db.TestingAnswer", b =>
                {
                    b.HasOne("CodeLearn.Db.Exercise", "Exercise")
                        .WithMany("TestingAnswers")
                        .HasForeignKey("ExerciseId")
                        .IsRequired()
                        .HasConstraintName("FK_testing_answer_exercise");

                    b.HasOne("CodeLearn.Db.TestingResult", "TestingResult")
                        .WithMany("TestingAnswers")
                        .HasForeignKey("TestingResultId")
                        .IsRequired()
                        .HasConstraintName("FK_testing_answer_testing_result");

                    b.Navigation("Exercise");

                    b.Navigation("TestingResult");
                });

            modelBuilder.Entity("CodeLearn.Db.TestingResult", b =>
                {
                    b.HasOne("CodeLearn.Db.Student", "Student")
                        .WithMany("TestingResults")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_testing_result_student");

                    b.HasOne("CodeLearn.Db.Testing", "Testing")
                        .WithMany("TestingResults")
                        .HasForeignKey("TestingId")
                        .IsRequired()
                        .HasConstraintName("FK_testing_result_testing");

                    b.Navigation("Student");

                    b.Navigation("Testing");
                });

            modelBuilder.Entity("CodeLearn.Db.TestMethodInfo", b =>
                {
                    b.HasOne("CodeLearn.Db.Exercise", "Exercise")
                        .WithMany("TestMethodInfos")
                        .HasForeignKey("ExerciseId")
                        .IsRequired()
                        .HasConstraintName("FK_test_method_info_exercise1");

                    b.HasOne("CodeLearn.Db.DataType", "ReturnType")
                        .WithMany("TestMethodInfos")
                        .HasForeignKey("ReturnTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_TestMethodsInfo_DataTypes");

                    b.Navigation("Exercise");

                    b.Navigation("ReturnType");
                });

            modelBuilder.Entity("CodeLearn.Db.TestMethodParameter", b =>
                {
                    b.HasOne("CodeLearn.Db.DataType", "DataType")
                        .WithMany("TestMethodParameters")
                        .HasForeignKey("DataTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ParametersTestMethods_DataTypes");

                    b.HasOne("CodeLearn.Db.TestMethodInfo", "TestMethodInfo")
                        .WithMany("TestMethodParameters")
                        .HasForeignKey("TestMethodInfoId")
                        .IsRequired()
                        .HasConstraintName("FK_ParametersTestMethods_TestMethodsInfo");

                    b.Navigation("DataType");

                    b.Navigation("TestMethodInfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CodeLearn.Db.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CodeLearn.Db.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeLearn.Db.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CodeLearn.Db.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingExercise", b =>
                {
                    b.HasOne("CodeLearn.Db.Testing", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_testing_exercise_testing");

                    b.HasOne("CodeLearn.Db.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .IsRequired()
                        .HasConstraintName("FK_testing_exercise_exercise");
                });

            modelBuilder.Entity("CodeLearn.Db.Student", b =>
                {
                    b.HasOne("CodeLearn.Db.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_student_group");

                    b.HasOne("CodeLearn.Db.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("CodeLearn.Db.Student", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CodeLearn.Db.Teacher", b =>
                {
                    b.HasOne("CodeLearn.Db.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("CodeLearn.Db.Teacher", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeLearn.Db.DataType", b =>
                {
                    b.Navigation("TestMethodInfos");

                    b.Navigation("TestMethodParameters");
                });

            modelBuilder.Entity("CodeLearn.Db.Exercise", b =>
                {
                    b.Navigation("TestMethodInfos");

                    b.Navigation("TestingAnswers");
                });

            modelBuilder.Entity("CodeLearn.Db.ExerciseType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("CodeLearn.Db.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CodeLearn.Db.TestCase", b =>
                {
                    b.Navigation("TestCaseParameters");
                });

            modelBuilder.Entity("CodeLearn.Db.Testing", b =>
                {
                    b.Navigation("TestingResults");
                });

            modelBuilder.Entity("CodeLearn.Db.TestingResult", b =>
                {
                    b.Navigation("TestingAnswers");
                });

            modelBuilder.Entity("CodeLearn.Db.TestMethodInfo", b =>
                {
                    b.Navigation("TestCases");

                    b.Navigation("TestMethodParameters");
                });

            modelBuilder.Entity("CodeLearn.Db.Student", b =>
                {
                    b.Navigation("TestingResults");
                });

            modelBuilder.Entity("CodeLearn.Db.Teacher", b =>
                {
                    b.Navigation("Testings");
                });
#pragma warning restore 612, 618
        }
    }
}
